# Generated by Django 3.0.1 on 2020-10-16 05:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='更新日时')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='创建日时')),
                ('recode_id', models.CharField(max_length=1000, verbose_name='记录id 为reoce表里的url')),
                ('metadata_name', models.CharField(max_length=10, verbose_name='元数据name 和recode_id为业务上的联合唯一')),
                ('content', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None, verbose_name='元数据内容')),
            ],
        ),
        migrations.CreateModel(
            name='Recode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='更新日时')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='创建日时')),
                ('title', models.CharField(max_length=100, verbose_name='内容标题')),
                ('domain', models.CharField(max_length=100, verbose_name='域名')),
                ('channel', models.CharField(max_length=5, verbose_name='频道')),
                ('url', models.CharField(max_length=1000, unique=True, verbose_name='url')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('content', models.CharField(blank=True, max_length=9999, null=True, verbose_name='内容正文')),
            ],
        ),
    ]
