# Generated by Django 3.0.1 on 2020-10-09 08:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='更新日时')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='创建日时')),
                ('recode_id', models.CharField(max_length=100, verbose_name='记录id')),
                ('metadat_type', models.CharField(max_length=5, verbose_name='元数据类型')),
                ('content', django.contrib.postgres.fields.jsonb.JSONField(default={'aa': []}, verbose_name='元数据内容')),
            ],
        ),
        migrations.CreateModel(
            name='Recode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='更新日时')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='创建日时')),
                ('title', models.CharField(max_length=100, verbose_name='内容标题')),
                ('domain', models.CharField(max_length=100, verbose_name='域名')),
                ('channel', models.CharField(max_length=5, verbose_name='频道')),
                ('url', models.CharField(blank=True, max_length=1000, null=True, verbose_name='url')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('data_set', django.contrib.postgres.fields.jsonb.JSONField(default={'Heatindex': '', 'content': '', 'index': ''}, verbose_name='内容详细信息')),
            ],
        ),
    ]
