# Generated by Django 3.0.1 on 2020-10-09 08:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collecter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='content',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'data': []}, verbose_name='元数据内容'),
        ),
    ]
