# Generated by Django 3.0.1 on 2020-10-11 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collecter', '0002_auto_20201009_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recode',
            name='data_set',
        ),
    ]
