# Generated by Django 3.0.1 on 2020-10-12 01:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collecter', '0003_remove_recode_data_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='recode',
            name='data_set',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'Heatindex': '', 'content': '', 'index': ''}, verbose_name='内容详细信息'),
        ),
    ]
