# Generated by Django 3.0.1 on 2020-10-12 02:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collecter', '0004_recode_data_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recode',
            name='data_set',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
