# Generated by Django 3.0.1 on 2020-10-12 02:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collecter', '0005_auto_20201012_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recode',
            name='data_set',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'content': ''}, verbose_name='内容详细信息'),
        ),
    ]
