# Generated by Django 3.0.1 on 2020-10-12 09:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collecter', '0006_auto_20201012_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadata',
            name='metadat_type',
        ),
        migrations.RemoveField(
            model_name='recode',
            name='data_set',
        ),
        migrations.AddField(
            model_name='metadata',
            name='metadat_name',
            field=models.CharField(default=123, max_length=10, verbose_name='元数据name 和recode_id为业务上的联合唯一'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recode',
            name='content',
            field=models.CharField(blank=True, max_length=9999, null=True, verbose_name='内容正文'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='content',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, verbose_name='元数据内容'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='recode_id',
            field=models.CharField(max_length=1000, verbose_name='记录id 为reoce表里的url'),
        ),
        migrations.AlterField(
            model_name='recode',
            name='url',
            field=models.CharField(max_length=1000, unique=True, verbose_name='url'),
        ),
    ]
