# Generated by Django 3.0.1 on 2020-10-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collecter', '0008_auto_20201012_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='metadat_name',
            field=models.CharField(max_length=10, verbose_name='元数据name 和recode_id为业务上的联合唯一'),
        ),
    ]
